### ISSUE TITLE
for F files

### ISSUE THREAD

**Issue by zschanghai** [AIR-DISCOVER/DQS3D#1]
Dear author of DQS3D:
I am glad to write to you!
------------------------------------------------------
I have a problem of huber_loss as follows:
"semi_single_stage_sparse.py", line 557, in _consistency_loss
bbox_feats_residual = torch.functional.F.huber_loss(student_bbox_feats[nbrs[:, 0], :], teacher_bbox_feats, reduction='none', delta=0.3)
------------------------------------------------------------------------------
as for the huber_loss is in the pytorch of 1.90 and the version after 1.90, and in the docker file the pytorch is 1.81, I suppose the F file was independently written by the author of DQS3D, for the F file is important for the project, I would like to request for F file. 

Yours sincerely!

**Comment by c7w** [comment]
Hi there,

In fact, we just installed the following pytorch version when reproducing FCAF3D. and it worked well :)
torch                    1.10.2+cu113
torchvision              0.11.3+cu113

**Comment by zschanghai** [comment]
Thank you for your help!
